### ISSUE TITLE
add required Node version to readme and/or engines to package.json

### ISSUE THREAD

**Issue by chrisbraddock** [drouian-m/express-chaos-middleware#1]
Package looks good, unfortunately I'm stuck on Node 14 and I think you're using 'timers/promises' [added in 15](https://nodejs.org/api/timers.html#timerspromisessettimeoutdelay-value-options).

**Comment by chrisbraddock** [comment]
Maybe just use something like this instead?

```JavaScript
const sleep = (ms) => new Promise(resolve => setTimeout(resolve, ms));

/**
 * Requests slowdown
 */
async function delay(req, res, next) {
  const maxDelay = req.options?.maxDelay || 500;
  const pause = Math.floor(Math.random() * maxDelay);
  debug(`rulesFunctions.delay - wait ${pause} ms`);
  await sleep(pause);
  next();
}
```

**Comment by ziggornif** [comment]
Hi Chris!

I just updated the waiting part without the timers/promises import 🙂

**Comment by chrisbraddock** [comment]
Nice! Thank-you!

**Comment by ziggornif** [comment]
I've just release again to fix an issue in the waiting function.

I took the opportunity to also add an example of code with a shell script that allows you to simulate calls

Version 1.1.1 should work fine for you
